---------------------- MODULE CompactHandoffPrivacy ----------------------
(***************************************************************************)
(* Models the privacy-gate invariant for suggestion-G in the               *)
(* session-equipment committee review:                                     *)
(*                                                                         *)
(*   "Persisting the /compact conversation summary as a handoff must not   *)
(*    leak user-origin tokens that are not already committed to the vault."*)
(*                                                                         *)
(* This is a worked example of formalization for a `confidence: low` claim *)
(* whose load-bearing-ness collapses without a precise invariant. The      *)
(* prose says "needs a privacy gate"; that's an aspiration, not a contract.*)
(* TLA+ forces us to say WHICH gate, on WHICH state, with WHICH guarantee. *)
(*                                                                         *)
(* If you have TLC installed, run with a 4-token, 2-vault-state model. The *)
(* invariant `PrivacySafe` should hold under `Sanitize` and FAIL under     *)
(* `PersistRaw` — that's the falsification protocol baked into the spec.   *)
(***************************************************************************)
EXTENDS Naturals, FiniteSets

CONSTANTS
    Tokens,             \* Universe of information units (sentences, snippets, etc.)
    UserOrigin,         \* Tokens whose origin is a user message in the conversation
    AgentOrigin,        \* Tokens whose origin is an agent response
    ToolOrigin          \* Tokens whose origin is a tool result

ASSUME UserOrigin \cup AgentOrigin \cup ToolOrigin \subseteq Tokens
ASSUME UserOrigin \cap AgentOrigin = {}
ASSUME UserOrigin \cap ToolOrigin = {}
ASSUME AgentOrigin \cap ToolOrigin = {}

VARIABLES
    summary,            \* Tokens currently in the /compact-generated summary
    vault,              \* Tokens that have been committed to git (vault SSOT)
    handoff             \* Tokens that have been written to the handoff file

vars == <<summary, vault, handoff>>

TypeOK ==
    /\ summary  \subseteq Tokens
    /\ vault    \subseteq Tokens
    /\ handoff  \subseteq Tokens

Init ==
    /\ summary  = {}
    /\ vault    = {}
    /\ handoff  = {}

(***************************************************************************)
(* Actions                                                                  *)
(***************************************************************************)

\* The conversation accumulates tokens of various origins.
ConverseUser(t) ==
    /\ t \in UserOrigin
    /\ summary' = summary \cup {t}
    /\ UNCHANGED <<vault, handoff>>

ConverseAgent(t) ==
    /\ t \in (AgentOrigin \cup ToolOrigin)
    /\ summary' = summary \cup {t}
    /\ UNCHANGED <<vault, handoff>>

\* Some tokens get committed to the vault during the session
\* (e.g., a Write that lands a memory file, a git commit).
CommitToVault(t) ==
    /\ t \in summary    \* must have surfaced in conversation
    /\ vault' = vault \cup {t}
    /\ UNCHANGED <<summary, handoff>>

(***************************************************************************)
(* The TWO competing /compact-handoff persistence models.                   *)
(***************************************************************************)

\* PersistRaw — the naive G-suggestion: dump the whole summary verbatim.
\* This is the version that LEAKS. Modeled here to prove the spec catches it.
PersistRaw ==
    /\ handoff' = handoff \cup summary
    /\ UNCHANGED <<summary, vault>>

\* Sanitize — the privacy-gated version: a user-origin token is only
\* persisted if it has already been committed to the vault. This is what
\* the privacy gate must enforce. AgentOrigin / ToolOrigin tokens flow
\* through unchanged (they were generated by the AI, not the human).
Sanitize ==
    LET safe == { t \in summary :
                    \/ t \in vault          \* user tokens that already landed in vault
                    \/ t \in AgentOrigin    \* agent-authored tokens
                    \/ t \in ToolOrigin }   \* tool outputs (separate consent question, modeled as OK)
    IN  /\ handoff' = handoff \cup safe
        /\ UNCHANGED <<summary, vault>>

(***************************************************************************)
(* Next-state relation. The two flavors of compact persistence are mutually *)
(* exclusive — pick one to model-check. Default Spec uses Sanitize.          *)
(***************************************************************************)

NextSafe ==
    \/ \E t \in Tokens : ConverseUser(t)
    \/ \E t \in Tokens : ConverseAgent(t)
    \/ \E t \in Tokens : CommitToVault(t)
    \/ Sanitize

NextUnsafe ==
    \/ \E t \in Tokens : ConverseUser(t)
    \/ \E t \in Tokens : ConverseAgent(t)
    \/ \E t \in Tokens : CommitToVault(t)
    \/ PersistRaw

Spec       == Init /\ [][NextSafe][_vars]    \* model the gated version
SpecUnsafe == Init /\ [][NextUnsafe][_vars]  \* model the leaky version

(***************************************************************************)
(* The invariant we want to hold across all reachable states.               *)
(*                                                                          *)
(*   For every user-origin token in the handoff, that token must already    *)
(*   be in the vault. (Agent and tool tokens are not gated — they didn't    *)
(*   originate with the human.)                                             *)
(***************************************************************************)
PrivacySafe ==
    \A t \in handoff :
        (t \in UserOrigin) => (t \in vault)

\* Sanity: the handoff is always a subset of what the agent saw.
HandoffBounded ==
    handoff \subseteq summary \cup AgentOrigin \cup ToolOrigin

(***************************************************************************)
(* Theorems (informal — TLC doesn't prove these, it model-checks them      *)
(* against finite instances).                                               *)
(***************************************************************************)
THEOREM SanitizePreservesPrivacy ==
    Spec => []PrivacySafe

THEOREM RawPersistViolatesPrivacy ==
    SpecUnsafe => <>~PrivacySafe   \* ◇¬P — eventually the invariant breaks

(***************************************************************************)
(* Notes on what this spec DOESN'T model (transparency for grilling):       *)
(*                                                                          *)
(*  1. Tool outputs are treated as auto-OK. In practice some tool outputs   *)
(*     contain user-derived data (e.g., a grep over user-authored notes).   *)
(*     A stricter spec would propagate origin through tools.                *)
(*  2. We model "commit" as a single set-add. Real git commits are atomic   *)
(*     groups; partial commits could break the gate if Sanitize runs        *)
(*     mid-stage.                                                           *)
(*  3. No notion of redaction — the spec only allows whole-token pass or    *)
(*     drop. A real privacy gate might paraphrase rather than drop.         *)
(*  4. No temporal ordering: a token committed AFTER the handoff was        *)
(*     persisted is not modeled as a privacy violation, but in practice     *)
(*     the order matters (the leak happened before the commit existed).    *)
(*                                                                          *)
(* These four limits are the load-bearing parts of suggestion-G that prose  *)
(* hand-waved over. They're now visible. Each one is a follow-up branch a   *)
(* reviewer can grill: "what about tool-derived user data?" "does Sanitize  *)
(* run atomically with the commit?" "is paraphrase a separate spec?" "how  *)
(* do we order the operations?"                                             *)
(***************************************************************************)
=============================================================================
